sentinel resolve-hostnames yes
sentinel announce-hostnames yes

sentinel monitor mymaster redis1 6379 1
sentinel auth-pass mymaster 1234

sentinel down-after-milliseconds mymaster 500
sentinel failover-timeout mymaster 60000
sentinel parallel-syncs mymaster 1
